# Generated by Django 4.2.9 on 2024-06-06 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatlog',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.FloatField(default=0)),
                ('user_id', models.CharField()),
                ('interaction_count', models.IntegerField(default=0)),
                ('user_typing_time', models.FloatField(default=0)),
                ('chatbot_inference_time', models.FloatField(default=0)),
                ('user_feedback', models.IntegerField(default=0)),
                ('escalation', models.IntegerField(default=0)),
                ('transcript', models.TextField(default='')),
                ('total_tokens', models.IntegerField(default=0)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('total_cost', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_id', models.CharField(max_length=125, unique=True)),
                ('conversation_history', models.JSONField(default=list)),
            ],
        ),
    ]
